FROM node:8.9

WORKDIR /app

# Drop just the package.json (and package-lock) so we can keep the Docker cache clean
# if we rarely change our packages (and avoid long build times)
COPY package*.json ./
RUN npm install --only=production

RUN npm install webpack-cli -D

# we will run the rest of Docker in a container, to keep this image size small