FROM golang:1.10

# build the full go path for src
# this will ensure imports will work correctly
RUN mkdir -p /go/src/github.com/callumj/docker-boilerplates/go/examples/webapp

# enter into this directory
WORKDIR /go/src/github.com/callumj/docker-boilerplates/go/examples/webapp

# we will then spin up a container to mount this directory, to keep this image small