FROM golang:1.10

# build the full go path for src
# this will ensure imports will work correctly
RUN mkdir -p /go/src/github.com/callumj/docker-boilerplates/go/examples/webapp

# enter into this directory and copy the whole contents of the directory
WORKDIR /go/src/github.com/callumj/docker-boilerplates/go/examples/webapp
COPY . .

# accept GIT_SHA as a build arg from Docker
# so we can pass into the Go compiler the value of gitSHA
# for X-App-Version
ARG GIT_SHA
ENV GIT_SHA ${GIT_SHA:-unknown}

# invoke the build process
RUN make build

# set the default command to run
CMD ["bin/app"]